### ISSUE TITLE
I believe the 'z' is a Typo after the '>' character as I receive the following error in AutoPkg

### ISSUE THREAD

**Issue by revpjbbq** [autopkg/bradclare-recipes#26]
https://github.com/autopkg/bradclare-recipes/blob/3b7e4d97f633c088f0b076467861282510bc5866/RingCentral/RingCentralPhone.pkg.recipe#L76

WARNING: plist error for /Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.bradclare-recipes/RingCentral/RingCentralPhone.pkg.recipe: Error Domain=NSCocoaErrorDomain Code=3840 "Encountered unexpected character z on line 76 while looking for open tag" UserInfo={NSDebugDescription=Encountered unexpected character z on line 76 while looking for open tag, kCFPropertyListOldStyleParsingError=Error Domain=NSCocoaErrorDomain Code=3840 "Malformed data byte group at line 1; invalid hex" UserInfo={NSDebugDescription=Malformed data byte group at line 1; invalid hex}}

Please let me know if I am in error.

Removing the 'z' from my local copy resolves the error.

**Comment by homebysix** [comment]
Cc @wegotoeleven, who last modified that recipe.
