### ISSUE TITLE
RingCentral has unset trust

### ISSUE THREAD

**Issue by delize** [autopkg/bradclare-recipes#4]
Currently the autopkg script fails with a TRUST INFO issue. If you override the copy that you have created, and set trust on the local machine you get this error:
Error: creating pkginfo for /Users/user/Library/AutoPkg/Cache/local.munki.RingCentral/downloads/RingCentral.dmg failed: Could not mount /Users/user/Library/AutoPkg/Cache/local.munki.RingCentral/downloads/RingCentral.dmg!

If you could please reverify the trust info against the download package after you modify it, and if you could please double check the URL path - as currently this is failing.

Thanks

**Comment by gregneagle** [comment]
Recipes do not have trust info. Only recipe overrides do. Recipe overrides are created by each user of autopkg -- they are not shared by recipe authors.

There may be issues with this recipe, but they aren't related to the lack of trust info, which is expected and normal.

Please review https://github.com/autopkg/autopkg/wiki/AutoPkg-and-recipe-parent-trust-info
