### ISSUE TITLE
MacsFanControl.download.recipe is failing code verification 

### ISSUE THREAD

**Issue by peetinc** [autopkg/bradclare-recipes#9]
Your MacsFanControl.download.recipe is failing code verification for a reason that I couldn't quite work out. I generated a new download recipe and attached it here with your identifier. Feel free to tease out what's not working in yours.

(I'm sorry I'm a bit of an idiot when it comes to GitHub and I'm not at all sure how to do a pull request)

[MacsFanControl.download.recipe.txt](https://github.com/autopkg/bradclare-recipes/files/3931342/MacsFanControl.download.recipe.txt)

Sorry for the .txt, but GitHub Doesn't allow .recipe.

**Comment by bradclare** [comment]
Hey Peet,

Thanks for troubleshooting, looks like the issue may have been case in the identifier line. I've uploaded your new version.
